[package]
name = "riri-file-dialog"
authors = [ "Rirurin" ]
version = "0.1.0"
edition = "2024"

[target.'cfg(windows)'.dependencies.windows]
version = "0.61.1"
features = [
    "Win32_System_Com",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common"
]